version: '3.8'

services:
  meetingplanner-postgres:
    container_name: project-planner-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - project-planner-postgres-volume:/var/lib/postgresql/data

  project-planner-app:
    container_name: project-planner-app
    image: rasmusilm/webapp:test
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "8000:80"
      
volumes:
  project-planner-postgres-volume:
  
  